### ISSUE TITLE
Question - why there is code duplication?

### ISSUE THREAD

**Issue by sarbbottam** [grafijs/grafi#1]
Great work!

---

I would like to understand the rational behind code duplication? For example:
[grafijs/grafi/grafi.js.blur](https://github.com/grafijs/grafi/blob/master/grafi.js#L174-L194)
[grafijs/grafi-blur/grafi-blur.js](https://github.com/grafijs/grafi-blur/blob/master/grafi-blur.js#L152-L172)

---

[grafi-blur](https://github.com/grafijs/grafi-blur) seems to be created much before [grafi](https://github.com/grafijs/grafi)

Is there any plan to discard the individual modules? Would love to know your rational.

**Comment by christianbundy** [comment]
From the README:

> WARNING : they code is pretty rough & documentation is not great. Gimme second as I go back to home form 2 weeks trip.

I assume this is unintentional, but maybe I'm wrong.
