### ISSUE TITLE
asp.net mvc5 using grafi.js

### ISSUE THREAD

**Issue by mnsaqib** [grafijs/grafi#5]
hello
i would like to use grafi.js on my asp.net mvc5 project, 

this is the place where my image will display

in my view

<div id="panel">

                    <img id="largeImage" src="" style="width:100%; height:100%;" title="" />
                    <div id="description"></div>
                

```
        </div>
```

this is my "Button" to invoke the grayscale 

 <li><a href="#"><img src="~/Images/button1.png" id="grayscale" title="grayscale" style="width:30px; height:30px;" /></a></li>

this is my javascript

<script>
        $(document).ready(function () {

    $("#grayscale").click(function () {

        $("#largeImage").grafi.grayscale(img, {mode: 'luma'});
    });
});
    </script>

but its not working

i am using google Chrome, and dont like to use Canvas, as all other my code will be a problem with canvas

any help would be highly appreciated

Thanks

**Comment by kosamari** [comment]
grafi.js takes JavaScript object in format of ImageData (has to have width, height, data), not Image file. 
You will need to pass something that look like this, not file name.

```
{
  width: 10
  height:10
  data: [255,255,255,255,..........]
}
```

If you are not familier with ImageData, maybe be this talk I gave would help.
https://www.youtube.com/watch?v=-6REd8lLsPM

If you want to avoid using Canvas, you need to use Image decoder library. I recommend googling `image decode [file format]`. You will then format data into `width, height, data` like the example above.
